spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: local # profile을 local로 활성화한다
    include: secret # secret을 include로 하여 application-secret.yml에 작성된 설정값을 읽어올 수 있다.